# This is a basic workflow that is manually triggered

name: Draft Release

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on: 
  push:
    branches: main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2
    
    - name: Download OpenSCAD
      run: sudo apt-get install -y openscad
    
    - name: Convert Files
      run: for file in "./parts/SCAD/*"; do openscad -o "./dist/${i%.*}.stl" "./parts/SCAD/$i"; done
      
    - name: Copy STEP files
      run: cp "./parts/STEP/*" "./dist/"
    
    - name: Zip Assets
      run: zip dist.zip ./dist/*
    
    - name: Draft Release
      uses: release-drafter/release-drafter@v5.12.1
      id: draft-release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
    - name: Upload Release Assets
      id: upload-release-asset 
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.draft-release.outputs.upload_url }}
        asset_path: ./dist.zip
        asset_name: Files.zip
        asset_content_type: application/zip
